---
#
# Playbook for installing NGINX Plus
# Requires valid certificate and key for NGINX Plus repositories
#
- name:
  file:
    dest:  /etc/ssl/nginx/ 
    state: directory
    owner: root

- name:  Copy Nginx Plus Certificate and Key
  copy:
    src:  "{{ item }}"
    dest: /etc/ssl/nginx
  with_items:
    - nginx-repo.crt
    - nginx-repo.key

- name:  Apt key for nginx
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    id:  ABF5BD827BD9BF62

- apt_repository:
    repo: deb https://plus-pkgs.nginx.com/ubuntu cosmic nginx-plus
    state: present

- name:  Install prerequisites
  apt:
    name:  "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https
      - lsb-release
      - ca-certificates

- name:  Install Nginx Plus apt configuration
  copy:
    src:  90nginx.dms
    dest: /etc/apt/apt.conf.d/90nginx

- name:  Install nginx-plus
  apt:
    name:  nginx-plus
    state: present
    update_cache: yes

- name:  Install nginx-plus modules
  apt:
    name:  "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - nginx-plus-module-ndk
      - nginx-plus-module-lua
  notify:
    - restart nginx

- name: Install nginx.conf
  template:
    src:  nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
